version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facturario-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    command: php artisan serve --host=0.0.0.0 --port=8000

  mysql:
    image: mysql:8.0
    container_name: facturario-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: facturario
      MYSQL_USER: facturario
      MYSQL_PASSWORD: facturario
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
